import { Shop } from '../models/shop.model';

export async function seedShops(
  users: { owners: any[] },
  categories: any[],
) {
  console.log('🏪 꽃집 데이터 생성 중...');

  const [owner1, owner2] = users.owners;
  const catMap: Record<string, string> = {};
  for (const c of categories) {
    catMap[c.slug] = c._id.toString();
  }

  const defaultHours = [
    { day: '월', open: '09:00', close: '21:00', isOpen: true },
    { day: '화', open: '09:00', close: '21:00', isOpen: true },
    { day: '수', open: '09:00', close: '21:00', isOpen: true },
    { day: '목', open: '09:00', close: '21:00', isOpen: true },
    { day: '금', open: '09:00', close: '21:00', isOpen: true },
    { day: '토', open: '10:00', close: '20:00', isOpen: true },
    { day: '일', open: '10:00', close: '18:00', isOpen: false },
  ];

  const shopsData = [
    {
      name: '꽃다발 정원',
      description: '강남에서 가장 사랑받는 플라워숍, 신선한 꽃으로 매일 새로운 꽃다발을 만듭니다.',
      owner: owner1._id,
      phone: '02-1234-5678',
      email: 'garden@flower.com',
      businessNumber: '123-45-67890',
      address: '서울특별시 강남구 테헤란로 152',
      addressDetail: '1층 꽃다발 정원',
      zipCode: '06236',
      location: { type: 'Point' as const, coordinates: [127.0365, 37.5000] },
      images: [],
      profileImage: '',
      categories: [catMap['birthday'], catMap['proposal'], catMap['celebration']],
      operatingHours: defaultHours,
      deliveryInfo: {
        isAvailable: true,
        fee: 3000,
        freeDeliveryOver: 50000,
        minOrderAmount: 25000,
        estimatedTime: '40~60분',
        maxDistance: 8,
      },
      rating: { average: 4.7, count: 128 },
      status: 'approved' as const,
      isOpen: true,
      isActive: true,
    },
    {
      name: '로즈마리 플라워',
      description: '홍대 감성 꽃집, 트렌디하고 유니크한 플라워 디자인을 추구합니다.',
      owner: owner1._id,
      phone: '02-2345-6789',
      email: 'rosemary@flower.com',
      businessNumber: '234-56-78901',
      address: '서울특별시 마포구 와우산로 29길 18',
      addressDetail: '로즈마리 플라워',
      zipCode: '04066',
      location: { type: 'Point' as const, coordinates: [126.9236, 37.5563] },
      images: [],
      profileImage: '',
      categories: [catMap['birthday'], catMap['seasonal'], catMap['basket']],
      operatingHours: [
        ...defaultHours.slice(0, 6),
        { day: '일', open: '11:00', close: '17:00', isOpen: true },
      ],
      deliveryInfo: {
        isAvailable: true,
        fee: 4000,
        freeDeliveryOver: 60000,
        minOrderAmount: 30000,
        estimatedTime: '30~50분',
        maxDistance: 5,
      },
      rating: { average: 4.9, count: 256 },
      status: 'approved' as const,
      isOpen: true,
      isActive: true,
    },
    {
      name: '블루밍 스튜디오',
      description: '종로의 프리미엄 플라워숍, 웨딩 부케와 이벤트 꽃 전문입니다.',
      owner: owner2._id,
      phone: '02-3456-7890',
      email: 'blooming@flower.com',
      businessNumber: '345-67-89012',
      address: '서울특별시 종로구 삼청로 75',
      addressDetail: '블루밍 스튜디오',
      zipCode: '03049',
      location: { type: 'Point' as const, coordinates: [126.9822, 37.5804] },
      images: [],
      profileImage: '',
      categories: [catMap['proposal'], catMap['celebration'], catMap['condolence']],
      operatingHours: defaultHours,
      deliveryInfo: {
        isAvailable: true,
        fee: 5000,
        freeDeliveryOver: 80000,
        minOrderAmount: 35000,
        estimatedTime: '50~70분',
        maxDistance: 10,
      },
      rating: { average: 4.5, count: 89 },
      status: 'approved' as const,
      isOpen: true,
      isActive: true,
    },
    {
      name: '해피 플라워',
      description: '잠실에서 20년 전통의 꽃집, 합리적인 가격으로 정성을 담은 꽃을 드립니다.',
      owner: owner2._id,
      phone: '02-4567-8901',
      email: 'happy@flower.com',
      businessNumber: '456-78-90123',
      address: '서울특별시 송파구 올림픽로 240',
      addressDetail: '해피 플라워',
      zipCode: '05556',
      location: { type: 'Point' as const, coordinates: [127.0830, 37.5145] },
      images: [],
      profileImage: '',
      categories: [catMap['birthday'], catMap['opening'], catMap['plant']],
      operatingHours: defaultHours,
      deliveryInfo: {
        isAvailable: true,
        fee: 3000,
        freeDeliveryOver: 40000,
        minOrderAmount: 20000,
        estimatedTime: '30~50분',
        maxDistance: 7,
      },
      rating: { average: 4.3, count: 312 },
      status: 'approved' as const,
      isOpen: true,
      isActive: true,
    },
    {
      name: '소담 꽃방',
      description: '이태원 감성 가득한 소담한 꽃방, 특별한 날을 위한 맞춤 꽃다발을 준비해드립니다.',
      owner: owner1._id,
      phone: '02-5678-9012',
      email: 'sodam@flower.com',
      businessNumber: '567-89-01234',
      address: '서울특별시 용산구 이태원로 200',
      addressDetail: '소담 꽃방 2층',
      zipCode: '04349',
      location: { type: 'Point' as const, coordinates: [126.9947, 37.5340] },
      images: [],
      profileImage: '',
      categories: [catMap['seasonal'], catMap['basket'], catMap['celebration']],
      operatingHours: [
        { day: '월', open: '10:00', close: '20:00', isOpen: true },
        { day: '화', open: '10:00', close: '20:00', isOpen: true },
        { day: '수', open: '10:00', close: '20:00', isOpen: true },
        { day: '목', open: '10:00', close: '20:00', isOpen: true },
        { day: '금', open: '10:00', close: '22:00', isOpen: true },
        { day: '토', open: '10:00', close: '22:00', isOpen: true },
        { day: '일', open: '12:00', close: '18:00', isOpen: true },
      ],
      deliveryInfo: {
        isAvailable: true,
        fee: 4000,
        freeDeliveryOver: 55000,
        minOrderAmount: 28000,
        estimatedTime: '40~60분',
        maxDistance: 6,
      },
      rating: { average: 4.8, count: 167 },
      status: 'approved' as const,
      isOpen: true,
      isActive: true,
    },
  ];

  const shops = await Shop.insertMany(shopsData);
  console.log(`  ✅ 꽃집 ${shops.length}개 생성 완료`);
  return shops;
}
